# Đây là một ghi chú cho toàn bộ tệp YAML

name: Cloudflare API Usage # Đây là ghi chú cho một dòng cụ thể

on:
  schedule:
    - cron: '25 1 * * *'  # Chạy cron job vào lúc 01:25 mỗi ngày
    - cron: '0 10 * * *'  # Chạy cron job vào lúc 10:00 mỗi ngày
    - cron: '0 17 * * *'  # Chạy cron job vào lúc 17:00 mỗi ngày
    - cron: '0 20 * * *'  # Chạy cron job vào lúc 20:00 mỗi ngày
  workflow_dispatch:  # Kích hoạt workflow bằng cách thủ công

jobs:
  query-and-send:
    runs-on: ubuntu-latest  # Sử dụng môi trường Ubuntu mới nhất

    env:
      API_EMAIL: ${{ secrets.API_EMAIL }}  # Email API từ secrets
      API_KEY: ${{ secrets.API_KEY }}  # API key từ secrets
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}  # ID tài khoản từ secrets
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Token bot từ secrets
      CHAT_ID: ${{ secrets.CHAT_ID }}  # ID chat từ secrets
      DAILY_LIMIT: 100000  # Giới hạn hàng ngày cho các yêu cầu

    steps:
      - name: Check out the repository  # Bước checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20  # Cài đặt Node.js phiên bản 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq  # Cài đặt jq để xử lý JSON
        run: sudo apt-get install -y jq

      - name: Query Cloudflare API and Send Telegram Message  # Truy vấn API và gửi tin nhắn Telegram
        run: |
          # Lấy ngày giờ hiện tại
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          START_DATE=$(echo $DATE | sed 's/T.*//')T00:00:00.000Z
          END_DATE=$(echo $DATE)

          # Định nghĩa query GraphQL
          QUERY='query getBillingMetrics($accountTag: String!, $filter: AccountWorkersInvocationsAdaptiveFilter_InputObject, $overviewFilter: AccountWorkersInvocationsAdaptiveFilter_InputObject) {
            viewer {
              accounts(filter: {accountTag: $accountTag}) {
                workersInvocationsAdaptive(limit: 10000, filter: $filter) {
                  sum {
                    duration
                    requests
                    subrequests
                    responseBodySize
                    errors
                  }
                  quantiles {
                    cpuTimeP50
                  }
                  dimensions {
                    usageModel
                  }
                }
                workersOverviewRequestsAdaptiveGroups(limit: 1000, filter: $overviewFilter) {
                  sum {
                    cpuTimeUs
                  }
                  dimensions {
                    usageModel
                  }
                }
                durableObjectsInvocationsAdaptiveGroups(limit: 10000, filter: $durableObjectFilter) {
                  sum {
                    requests
                  }
                }
                durableObjectsPeriodicGroups(limit: 10000, filter: $durableObjectFilter) {
                  sum {
                    activeTime
                  }
                }
              }
            }
          }'

          # Gửi request tới Cloudflare API
          RESPONSE=$(curl -s -X POST 'https://api.cloudflare.com/client/v4/graphql' \
            -H 'Content-Type: application/json' \
            -H "X-Auth-Email: $API_EMAIL" \
            -H "X-Auth-Key: $API_KEY" \
            --data-raw "$(jq -n \
              --arg accountTag "$ACCOUNT_ID" \
              --arg startDate "$START_DATE" \
              --arg endDate "$END_DATE" \
              --argjson filter "{\"datetime_geq\": \"$START_DATE\", \"datetime_leq\": \"$END_DATE\"}" \
              --argjson overviewFilter "{\"datetime_geq\": \"$START_DATE\", \"datetime_leq\": \"$END_DATE\"}" \
              --argjson durableObjectFilter "{\"datetimeHour_geq\": \"$START_DATE\", \"datetimeHour_leq\": \"$END_DATE\"}" \
              --arg query "$QUERY" \
              '{query: $query, variables: {accountTag: $accountTag, filter: $filter, overviewFilter: $overviewFilter, durableObjectFilter: $durableObjectFilter}}')")

          echo "Cloudflare API Response: $RESPONSE"  # In ra phản hồi từ Cloudflare API

          # Kiểm tra xem có dữ liệu tài khoản không
          if [ "$(echo $RESPONSE | jq -r '.data.viewer.accounts | length')" -eq 0 ]; then
            echo "No accounts data found. Please check your ACCOUNT_ID."
            exit 1
          fi

          # Lấy số lượng requests
          REQUESTS=$(echo $RESPONSE | jq '.data.viewer.accounts[0].workersInvocationsAdaptive[0].sum.requests // 0')
          if [ "$REQUESTS" == "null" ]; then
            echo "No request data found. Please check your query and ensure there is data in the specified time range."
            exit 1
          fi

          # Tính phần trăm sử dụng
          USAGE_PERCENTAGE=$(echo "scale=2; ($REQUESTS / $DAILY_LIMIT) * 100" | bc)

          # Định dạng ngày giờ và tin nhắn
          FORMATTED_DATE=$(TZ=Asia/Ho_Chi_Minh date +"%d-%m-%Y %H:%M:%S")
          MESSAGE=$(printf "⏰ Thông báo lúc: %s\n✅ Số lượng truy vấn: %d / %d\n💯 Phần trăm sử dụng: %.2f%%" "$FORMATTED_DATE" "$REQUESTS" "$DAILY_LIMIT" "$USAGE_PERCENTAGE")
          ENCODED_MESSAGE=$(echo "$MESSAGE" | jq -sRr @uri)

          # Gửi tin nhắn tới Telegram
          TELEGRAM_RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID&text=$ENCODED_MESSAGE")

          # Kiểm tra phản hồi từ Telegram
          if [ "$(echo $TELEGRAM_RESPONSE | jq -r '.ok')" != "true" ]; then
            echo "Failed to send Telegram message."
            exit 1
          fi

          echo "Message sent successfully!"  # In ra thông báo gửi tin nhắn thành công
